// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using entity;

#nullable disable

namespace entity.Migrations
{
    [DbContext(typeof(EgitimContext))]
    [Migration("20230417065056_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("entity.Egitmen", b =>
                {
                    b.Property<int>("egitmenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("egitmenAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("egitmenSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("egitmenYas")
                        .HasColumnType("INTEGER");

                    b.HasKey("egitmenId");

                    b.ToTable("egitmenler");
                });

            modelBuilder.Entity("entity.Kurs", b =>
                {
                    b.Property<int>("kursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("kursAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("kursId");

                    b.ToTable("kurslar");
                });

            modelBuilder.Entity("entity.Ogrenci", b =>
                {
                    b.Property<int>("ogrenciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ogrenciAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ogrenciSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ogrenciId");

                    b.ToTable("ogrenciler");
                });

            modelBuilder.Entity("entity.Personel", b =>
                {
                    b.Property<int>("perId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("perAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("perSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("perId");

                    b.ToTable("personeller");
                });

            modelBuilder.Entity("entity.Sinif", b =>
                {
                    b.Property<int>("sinifId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("sinifNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("sinifId");

                    b.ToTable("siniflar");
                });
#pragma warning restore 612, 618
        }
    }
}
